// Generated by CoffeeScript 1.3.1
(function() {
  var Item, List;

  Item = require('./item');

  List = (function() {

    List.name = 'List';

    function List(list_items) {
      var item;
      this.items = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = list_items.length; _i < _len; _i++) {
          item = list_items[_i];
          if (item !== '') {
            _results.push(new Item(item));
          }
        }
        return _results;
      })();
    }

    List.prototype.add = function(text) {
      return this.items.push(new Item(text));
    };

    List.prototype.remove = function(index) {
      return this.items.splice(index, 1);
    };

    List.prototype.toString = function() {
      var item, str, _i, _len, _ref;
      console.log("pouet");
      str = '';
      _ref = this.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        str += item.toString() + '\n';
      }
      return str;
    };

    return List;

  })();

  module.exports = List;

}).call(this);
