// Generated by CoffeeScript 1.3.1
(function() {
  var Item, List;

  Item = require('./item');

  List = List = (function() {

    List.name = 'List';

    function List(list_items) {
      var item;
      if (list_items) {
        this.tasks = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = list_items.length; _i < _len; _i++) {
            item = list_items[_i];
            if (item !== '') {
              _results.push(new Item(item));
            }
          }
          return _results;
        })();
      }
      if (this.tasks == null) {
        this.tasks = [];
      }
    }

    List.prototype.add = function(text_or_task) {
      if (typeof text_or_task === 'string') {
        this.tasks.push(new Item("[ ] " + text_or_task));
      } else {
        this.tasks.push(text_or_task);
      }
      return this.sort_by_prio();
    };

    List.prototype.removeAt = function(index) {
      var task;
      task = this.tasks.splice(index, 1);
      return task;
    };

    List.prototype.sort_by_prio = function() {
      return this.tasks.sort(function(a, b) {
        if (a.priority < b.priority) {
          return 1;
        }
        if (a.priority > b.priority) {
          return -1;
        }
        return 0;
      });
    };

    List.prototype.get = function(index) {
      return this.tasks[index];
    };

    List.prototype.toFile = function() {
      var item, str, _i, _len, _ref;
      str = '';
      _ref = this.tasks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        str += item.toFile();
        str += '\n';
      }
      return str;
    };

    List.prototype.toString = function() {
      var count, item, length, str, _i, _len, _ref;
      length = this.tasks.length;
      count = 0;
      str = '';
      _ref = this.tasks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        count++;
        str += ("" + count + " ").yellow;
        str += item.toString();
        str += '\n';
      }
      if (count !== length) {
        str += ("" + count + " of " + length + " tasks shown").bold;
      }
      return str;
    };

    return List;

  })();

  module.exports = List;

}).call(this);
