// Generated by CoffeeScript 1.3.1
(function() {
  var processCommand;

  exports.VERSION = '0.0.1';

  processCommand = function(buffer) {
    return console.log(buffer);
  };

  exports.exec = function(buffer) {
    return processCommand(buffer);
  };

}).call(this);
